---

- name: "include os-specific variables"
  include_vars: "1-{{ ansible_lsb['id'] }}-{{ ansible_facts ['distribution_release'] }}.yml"
  register: result

- name: variabel that is include
  debug:
    var: result[ansible_included_var_files]

- name: "Include task for OS family"
  include_tasks: "01-General-{{ ansible_os_family }}.yml" #-{{ ansible_facts ['distribution_release'] }}
  #distribution

- name: "Include task for distro"
  include_tasks: "02-distro-{{ ansible_lsb['id'] }}.yml" #-{{ ansible_facts ['distribution_release'] }}
  #distribution
  ignore_errors: yes
